language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
before_install:
  - pip install --user cpp-coveralls
before_script:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.9"; export GCOV="gcov-4.9"; fi
script:
  - make test
after_success:
  - make run_gcov
  - coveralls -x gcov -n
