language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - make get_test_dependencies
before_script:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"; fi
after_success:
  - make run_gcov
  - bash <(curl -s https://codecov.io/bash)
