addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - make get_test_dependencies
  - if [ $CXX == "g++"]; then export CXX=g++-4.8; fi
language: cpp
compiler:
  - clang
  - gcc