language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - ggcov
install:
  - sudo pip install cpp-coveralls
  - make get_test_dependencies
before_script:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.9"; fi
script:
  - make test
after_success:
  - gcov --version
  - g++ --version
  - make run_gcov
  - ls /usr/bin | grep gcov
  - coveralls -n
