language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - sudo pip install cpp-coveralls
install:
  - make get_test_dependencies
before_script:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"; fi
script:
  - make test
after_success:
  - coveralls -e '._test\.cpp' -e gtest/ -e gmock/ --gcov-options '\-lp'
