language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - lcov
before_install:
  - sudo pip install cpp-coveralls
  - gem install coveralls-lcov
install:
  - make get_test_dependencies
before_script:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"; fi
after_success:
  # - lcov -r gmock/ -r gtest/ -r test --compat-libtool --directory . --capture --output-file coverage.info
  # - cat coverage.info
  # - coveralls-lcov coverage.info
  - bash scripts/get_code_coverage_dependencies.sh
  - make generate_code_coverage_report_xml
  - coveralls-lcov gcovr-report.xml
