#!/bin/bash

set -e

# git hooks directory
GIT_HOOKS_DIR=$(pwd)'/git_hooks/'

# fix whitespace
printf "\nCleaning up trailing whitespace and adding missing newlines\n"
$GIT_HOOKS_DIR'check_whitespace.sh'

# run tests
printf "\nRunning tests\n"
$GIT_HOOKS_DIR'run_tests.sh'

# check code coverage
printf "\nGenerating code coverage reports\n"
$GIT_HOOKS_DIR'check_code_coverage.sh'
